[env:fobe-meshlink-r1lg]
extends = nrf52840_base
board = fobe-devkit-nrf52840
build_flags =
  ${nrf52840_base.build_flags}
  -Ivariants/fobe_meshlink_r1lg
  -DFOBE_MESHLINK_R1LG
  -DUSE_EINK
  -DEINK_DISPLAY_MODEL=GxEPD2_213_B74
  -DEINK_WIDTH=250
  -DEINK_HEIGHT=122
  -DUSE_EINK_DYNAMICDISPLAY
  -DEINK_LIMIT_FASTREFRESH=10
  -DEINK_LIMIT_RATE_BACKGROUND_SEC=30
  -DEINK_LIMIT_RATE_RESPONSIVE_SEC=1
  -DEINK_BACKGROUND_USES_FAST
  -DEINK_HASQUIRK_GHOSTING
  -DEINK_HASQUIRK_WEAKFASTREFRESH
  -DRADIOLIB_EXCLUDE_SX128X=1
  -DRADIOLIB_EXCLUDE_SX127X=1
  -DRADIOLIB_EXCLUDE_LR11X0=1
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/fobe_meshlink_r1lg>
board_build.ldscript = src/platform/nrf52/nrf52840_s140_v7.ld
lib_deps = 
  ${nrf52840_base.lib_deps}
  https://github.com/meshtastic/GxEPD2#b202ebfec6a4821e098cf7a625ba0f6f2400292d
debug_tool = cmsis-dap
;debug_init_break = tbreak loop

[env:fobe-meshlink-r1lg-inkhud]
extends = nrf52840_base, inkhud
board = fobe-devkit-nrf52840
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/fobe_meshlink_r1lg> ${inkhud.build_src_filter}
board_build.ldscript = src/platform/nrf52/nrf52840_s140_v7.ld
build_flags = 
  ${inkhud.build_flags}
  ${nrf52840_base.build_flags}
  -Ivariants/fobe_meshlink_r1lg
  -DPRIVATE_HW
  -DFOBE_MESHLINK_R1LG
  -DRADIOLIB_EXCLUDE_SX128X=1
  -DRADIOLIB_EXCLUDE_SX127X=1
  -DRADIOLIB_EXCLUDE_LR11X0=1
lib_deps =
  ${inkhud.lib_deps} ; InkHUD libs first, so we get GFXRoot instead of AdafruitGFX
  ${nrf52840_base.lib_deps}
debug_tool = cmsis-dap
;debug_init_break = tbreak loop