[env:fobe-meshlink-solar-power]
extends = nrf52840_base
board = fobe-feather-nrf52840
build_src_filter = ${nrf52_base.build_src_filter} +<../variants/fobe_meshlink_solar_power>
board_build.ldscript = src/platform/nrf52/nrf52840_s140_v7.ld
build_flags = 
  ${nrf52840_base.build_flags}
  -Ivariants/fobe_meshlink_solar_power
  -DPRIVATE_HW
  -DFOBE_MESHLINK_SOLAR_POWER
  -DRADIOLIB_EXCLUDE_SX128X=1
  -DRADIOLIB_EXCLUDE_SX127X=1
  -DRADIOLIB_EXCLUDE_LR11X0=1
lib_deps =
  ${nrf52840_base.lib_deps}
debug_tool = cmsis-dap
debug_init_break = tbreak loop