name: Setup Build Base Composite Action
description: Base build actions for Meshtastic Platform IO steps

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        submodules: recursive
        ref: ${{github.event.pull_request.head.ref}}
        repository: ${{github.event.pull_request.head.repo.full_name}}

    - name: Uncomment build epoch
      shell: bash
      run: |
        sed -i 's/#-DBUILD_EPOCH=$UNIX_TIME/-DBUILD_EPOCH=$UNIX_TIME/' platformio.ini

    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get -y update --fix-missing
        sudo apt-get install -y cppcheck libbluetooth-dev libgpiod-dev libyaml-cpp-dev lsb-release

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Gathering Python tools information
      id: python-info
      shell: bash
      run: |
        echo "python-version=$(python --version | cut -d' ' -f2)" >> $GITHUB_OUTPUT

    - name: Cache Python tools
      uses: runs-on/cache@v4
      with:
        path: |
          ~/.cache/pip
          .github/actions/**
          **.ini
        key: setup-python-${{ runner.os }}-${{ runner.arch }}-python-${{ steps.python-info.outputs.python-version }}-pip-${{ hashFiles('**/requirements.txt', '**.ini', '.github/actions/**') }}
        restore-keys: |
          setup-python-${{ runner.os }}-${{ runner.arch }}-python-${{ steps.python-info.outputs.python-version }}-pip-

    - name: Upgrade python tools
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -U --no-build-isolation --no-cache-dir "setuptools<72"
        pip install -U platformio adafruit-nrfutil --no-build-isolation
        pip install -U poetry --no-build-isolation
        pip install -U meshtastic --pre --no-build-isolation

    - name: Upgrade platformio
      shell: bash
      run: |
        pio upgrade
