[env:fobe-mesh-serial]
board_level = extra
extends = esp32c3_base
upload_protocol = esptool
board = esp32-c3-devkitm-1
board_upload.use_1200bps_touch = yes
board_upload.wait_for_upload_port = yes
board_upload.require_upload_port = yes
build_flags = 
  ${esp32_base.build_flags}
  -I variants/fobe_mesh_serial
  -D FOBE_MESH_SERIAL
  -D PRIVATE_HW
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D MESHTASTIC_EXCLUDE_I2C=1
  -D MESHTASTIC_EXCLUDE_ENVIRONMENTAL_SENSOR=1
lib_deps = ${esp32c3_base.lib_deps}