name: Setup Python with S3 cache
description: Install and restore Python dependencies using S3 cache

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x

    - name: Gathering Python tools information
      id: python-info
      shell: bash
      run: |
        echo "python-version=$(python --version | cut -d' ' -f2)" >> $GITHUB_OUTPUT

    - name: Cache Python tools
      uses: runs-on/cache@v4
      with:
        path: ~/.cache/pip
        key: setup-python-${{ runner.os }}-${{ runner.arch }}-python-${{ steps.python-info.outputs.python-version }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          setup-python-${{ runner.os }}-${{ runner.arch }}-python-${{ steps.python-info.outputs.python-version }}-pip-
