name: Daily Setup

permissions:
  contents: read

concurrency:
  group: daily-setup-workflow
  cancel-in-progress: false

on:
  schedule:
    - cron: 0 16 * * *
  workflow_dispatch:

env:
  FOBE_S3_ARTIFACT_BUCKET: fobe-gars-artifact
  FOBE_S3_ARTIFACT_HOST: ${{ secrets.FOBE_GARS_S3_ENDPOINT_HOST }}
  FOBE_S3_ARTIFACT_PORT: ${{ secrets.FOBE_GARS_S3_ENDPOINT_PORT }}
  FOBE_S3_ARTIFACT_ACCESS_KEY: ${{ secrets.FOBE_GARS_S3_ACCESS_KEY }}
  FOBE_S3_ARTIFACT_SECRET_KEY: ${{ secrets.FOBE_GARS_S3_SECRET_KEY }}
  RUNS_ON_S3_BUCKET_CACHE: fobe-gars-cache
  RUNS_ON_AWS_REGION: cn-sounth-fobe-1
  AWS_ACCESS_KEY_ID: ${{ secrets.FOBE_GARS_S3_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.FOBE_GARS_S3_SECRET_KEY }}
  AWS_ENDPOINT_URL: "http://${{ secrets.FOBE_GARS_S3_ENDPOINT_HOST }}:${{ secrets.FOBE_GARS_S3_ENDPOINT_PORT }}"
  RUNS_ON_S3_FORCE_PATH_STYLE: "true"

jobs:
  setup:
    if: github.ref == 'refs/heads/workflow'
    strategy:
      fail-fast: false
      matrix:
        platform:
          - esp32
          - esp32s3
          - esp32c3
          - esp32c6
          - nrf52840
          - rp2040
          - rp2350
          - stm32
          - check
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: ./.github/actions/setup-python

      - name: Setup PlatformIO
        uses: ./.github/actions/setup-platformio
        with:
          platform: ${{ matrix.platform }}
          check-only: false
          read-only: false
