name: Test MinIO Artifact Upload & Download

on:
  workflow_dispatch:

env:
  FOBE_S3_ARTIFACT_BUCKET: fobe-gars-artifact
  FOBE_S3_ARTIFACT_HOST: ${{ secrets.FOBE_GARS_S3_ENDPOINT_HOST }}
  FOBE_S3_ARTIFACT_PORT: ${{ secrets.FOBE_GARS_S3_ENDPOINT_PORT }}
  FOBE_S3_ARTIFACT_ACCESS_KEY: ${{ secrets.FOBE_GARS_S3_ACCESS_KEY }}
  FOBE_S3_ARTIFACT_SECRET_KEY: ${{ secrets.FOBE_GARS_S3_SECRET_KEY }}
  RUNS_ON_S3_BUCKET_CACHE: fobe-gars-cache
  RUNS_ON_AWS_REGION: cn-sounth-fobe-1
  AWS_ACCESS_KEY_ID: ${{ secrets.FOBE_GARS_S3_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.FOBE_GARS_S3_SECRET_KEY }}
  AWS_ENDPOINT_URL: "http://${{ secrets.FOBE_GARS_S3_ENDPOINT_HOST }}:${{ secrets.FOBE_GARS_S3_ENDPOINT_PORT }}"
  RUNS_ON_S3_FORCE_PATH_STYLE: "true"

jobs:
  test-artifacts:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload bin/*.sh
        uses: ./.github/actions/upload-artifact
        with:
          name: bin-sh
          path: ./bin/*.sh
          overwrite: "true"

      - name: Upload debian
        uses: ./.github/actions/upload-artifact
        with:
          name: debian
          path: ./debian
          overwrite: "true"

      - name: Download all artifacts to up-test
        uses: ./.github/actions/download-artifact
        with:
          path: up-test
          merge-multiple: "false"
